version: '3'
services:

  repo:
    image: theclocktwister/apt-repo:latest
    container_name: repo
    ports:
      - 8000:80   # HTTP default port
    volumes:
      # ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼ required mount points ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼

      # This is the folder where you just dump all your .deb files.
      # We mount with R/W, because the image automatically renames
      # the .deb files to the correct Debian format
      - ./debs:/http/repo/debs:rw

      # ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼ optional mount points ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼

      # (optional) Log folder for access and error logs
      # This where all the Nginx logs go. This can get quite full
      # over time. Of cause, it needs read and write permissions.
      - ./logs:/logs:rw

      # (optional) GPG signing key
      # Read-only, so noone can mess with our key file. The key is
      # needed if you want to host a signed repo. It's not hard to
      # generate a simple gpg key, so I highly suggest you dot it!
      - ./private.key:/private.key:ro

      # (toptional) if you want a custom NGINX config
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
